version: '3.9'

services:
  go-progres:
    build:
      context: .
    ports:
      - "3000:3000"
  postgres-db:
    env_file: .env
    image: postgres
    volumes:
      - pgvol:/data/db/
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"

volumes:
  pgvol:

# networks:
#   pgnet:
